/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeblakRouteImport } from './routes/seblak'
import { Route as SeblakIndexRouteImport } from './routes/seblak.index'
import { Route as SeblakCheckoutRouteImport } from './routes/seblak.checkout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeblakRoute = SeblakRouteImport.update({
  id: '/seblak',
  path: '/seblak',
  getParentRoute: () => rootRouteImport,
} as any)
const SeblakIndexRoute = SeblakIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SeblakRoute,
} as any)
const SeblakCheckoutRoute = SeblakCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => SeblakRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/seblak': typeof SeblakRouteWithChildren
  '/seblak/checkout': typeof SeblakCheckoutRoute
  '/seblak/': typeof SeblakIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/seblak/checkout': typeof SeblakCheckoutRoute
  '/seblak': typeof SeblakIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/seblak': typeof SeblakRouteWithChildren
  '/seblak/checkout': typeof SeblakCheckoutRoute
  '/seblak/': typeof SeblakIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/seblak' | '/seblak/checkout' | '/seblak/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/seblak/checkout' | '/seblak'
  id: '__root__' | '/' | '/seblak' | '/seblak/checkout' | '/seblak/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SeblakRoute: typeof SeblakRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seblak': {
      id: '/seblak'
      path: '/seblak'
      fullPath: '/seblak'
      preLoaderRoute: typeof SeblakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seblak/': {
      id: '/seblak/'
      path: '/'
      fullPath: '/seblak/'
      preLoaderRoute: typeof SeblakIndexRouteImport
      parentRoute: typeof SeblakRoute
    }
    '/seblak/checkout': {
      id: '/seblak/checkout'
      path: '/checkout'
      fullPath: '/seblak/checkout'
      preLoaderRoute: typeof SeblakCheckoutRouteImport
      parentRoute: typeof SeblakRoute
    }
  }
}

interface SeblakRouteChildren {
  SeblakCheckoutRoute: typeof SeblakCheckoutRoute
  SeblakIndexRoute: typeof SeblakIndexRoute
}

const SeblakRouteChildren: SeblakRouteChildren = {
  SeblakCheckoutRoute: SeblakCheckoutRoute,
  SeblakIndexRoute: SeblakIndexRoute,
}

const SeblakRouteWithChildren =
  SeblakRoute._addFileChildren(SeblakRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SeblakRoute: SeblakRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
